// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRfJkw6hfegiw5xaQU0eLuLLnk80Ex1A',
    appId: '1:764075172788:web:b39e3aa74f2a47ac74c8e1',
    messagingSenderId: '764075172788',
    projectId: 'learningapp-3d07b',
    authDomain: 'learningapp-3d07b.firebaseapp.com',
    storageBucket: 'learningapp-3d07b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6m7CfWI_mDfLotAgxeHdd_yc9OoKG3Fc',
    appId: '1:764075172788:android:c56b7234c0c7589f74c8e1',
    messagingSenderId: '764075172788',
    projectId: 'learningapp-3d07b',
    storageBucket: 'learningapp-3d07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeIWX2AsQtqbvhA8c1CusPCJmR8RwPIUA',
    appId: '1:764075172788:ios:d527fe0ea11c4b5f74c8e1',
    messagingSenderId: '764075172788',
    projectId: 'learningapp-3d07b',
    storageBucket: 'learningapp-3d07b.appspot.com',
    iosBundleId: 'com.example.challengeLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeIWX2AsQtqbvhA8c1CusPCJmR8RwPIUA',
    appId: '1:764075172788:ios:239758e56b512ceb74c8e1',
    messagingSenderId: '764075172788',
    projectId: 'learningapp-3d07b',
    storageBucket: 'learningapp-3d07b.appspot.com',
    iosBundleId: 'com.example.challengeLearningApp.RunnerTests',
  );
}
